# XXX: DO NOT USE _ (underscore) in config variable names since
#   viper substitutes the dots . with _ to load config from environment variables.
#
#   Environment variables used to override these settings should have a prefix OKCTL_

binaries:
  - name: eksctl
    version: 0.18.0
    bufferSize: 100mb
    urlPattern: https://github.com/weaveworks/eksctl/releases/download/#{ver}/eksctl_#{os}_#{arch}.tar.gz
    archive:
      type: .tar.gz
      target: eksctl
    checksums:
      - os: darwin
        arch: amd64
        type: sha256
        digest: fc320f3e52adef9f8d06a98f1996801ee3b59d1d74bac11e24123f593875a344
      - os: linux
        arch: amd64
        type: sha256
        digest: a8f83394a12051bd6bf539dca7db2005237d36c6b1a67073bcf2070d034356f0